from SingleLinkedList import *

LL1 = LinkedList()
Node1 = LL1.Prepend("I use Arch BTW")
Node2 = LL1.Prepend("Abo obaidah amk")
Node3 = LL1.Insert(LL1.head, 6.2)
Node4 = LL1.Insert(LL1.head.next, 8)
Node5 = LL1.Append(1)
Node6 = LL1.Append(4.7)
LL1.print_list()
print("\n")
LL1.delete(4.7)
LL1.print_list()
print("\n")
LL1.search("I use Arch BTW")
